version: '3'
services:
  web:
    image: nginx
    ports:
      - 8081:80
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network 
  app:
    build:
      context: .
      dockerfile: Dockerfile
      depends_on:
        - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network
     
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: flaskdbuser
      POSTGRES_DB: flaskdb
      POSTGRES_PASSWORD: passw@123
    networks:  
      - app-network
volumes:
  postgres_data:
networks:
  app-network:
    driver: bridge
